In [1]:
import numpy as np 
import pandas as pd 
#from sklearn.neural_network import MLPClassifier
#from sklearn import svm
#from sklearn.preprocessing import LabelEncoder
#from sklearn.preprocessing import Imputer
#from sklearn import preprocessing
#from sklearn.model_selection import train_test_split
#from sklearn.preprocessing import MinMaxScaler
#from sklearn.preprocessing import LabelBinarizer
#from sklearn.metrics import confusion_matrix
#from sklearn.metrics import classification_report
#from datetime import datetime
import matplotlib.pyplot as plt
%matplotlib inline

In [74]:
data_train = pd.read_csv("train.csv")
print("Train data shape = " + str(data_train.shape))

original_training_rows = data_train.shape[0]
data_train.head(n=5)

Train data shape = (891, 12)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [112]:
data_test = pd.read_csv("test.csv")
print("Test data shape = " + str(data_test.shape))
data_test.head(n=5)

Test data shape = (418, 11)


PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [116]:
data_test.PassengerId.values

array([ 892,  893,  894,  895,  896,  897,  898,  899,  900,  901,  902,
        903,  904,  905,  906,  907,  908,  909,  910,  911,  912,  913,
        914,  915,  916,  917,  918,  919,  920,  921,  922,  923,  924,
        925,  926,  927,  928,  929,  930,  931,  932,  933,  934,  935,
        936,  937,  938,  939,  940,  941,  942,  943,  944,  945,  946,
        947,  948,  949,  950,  951,  952,  953,  954,  955,  956,  957,
        958,  959,  960,  961,  962,  963,  964,  965,  966,  967,  968,
        969,  970,  971,  972,  973,  974,  975,  976,  977,  978,  979,
        980,  981,  982,  983,  984,  985,  986,  987,  988,  989,  990,
        991,  992,  993,  994,  995,  996,  997,  998,  999, 1000, 1001,
       1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012,
       1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023,
       1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034,
       1035, 1036, 1037, 1038, 1039, 1040, 1041, 10

In [4]:
# Look for Nan's in the train data

data_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
# Look for Nan's in the test data

data_test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [7]:
# separate column "Survived" from the others in the train data and save it to use as y
data_train_y = data_train.Survived
data_train_y = data_train_y.values
data_train_y = data_train_y.reshape(data_train_y.shape[0],1)

print("data_train_y shape: " + str(data_train_y.shape))
print(data_train_y[:5])

data_train_y shape: (891, 1)
[[0]
 [1]
 [1]
 [1]
 [0]]


In [19]:
# Drop column "Survived" from the training data and join the training data with the test data

data_train_x = data_train.drop(columns = ['Survived'])

data_x = np.concatenate((data_train_x, data_test), axis = 0)

print("data_x: " + str(data_x.shape))
print(data_x[:5])

data_x: (1309, 11)
[[1 3 'Braund, Mr. Owen Harris' 'male' 22.0 1 0 'A/5 21171' 7.25 nan 'S']
 [2 1 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)' 'female' 38.0 1
  0 'PC 17599' 71.2833 'C85' 'C']
 [3 3 'Heikkinen, Miss. Laina' 'female' 26.0 0 0 'STON/O2. 3101282' 7.925
  nan 'S']
 [4 1 'Futrelle, Mrs. Jacques Heath (Lily May Peel)' 'female' 35.0 1 0
  '113803' 53.1 'C123' 'S']
 [5 3 'Allen, Mr. William Henry' 'male' 35.0 0 0 '373450' 8.05 nan 'S']]


In [25]:
# Analysis and preparation of column "Pclass":

pclass = data_x[:,1]
pclass_onehot = pd.get_dummies(pclass)
pclass_onehot = pclass_onehot.values

print(pclass_onehot[:5])

[[0 0 1]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]]


In [54]:
# Analysis and preparation of column "Name":

name = data_x[:,2]
print(name[:5])
#complete later: look for titles and maybe surnames

['Braund, Mr. Owen Harris'
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'
 'Heikkinen, Miss. Laina' 'Futrelle, Mrs. Jacques Heath (Lily May Peel)'
 'Allen, Mr. William Henry']


In [37]:
# Analysis and preparation of column "Sex":

sex = data_x[:,3]
sex_onehot = pd.get_dummies(sex)
sex_onehot = sex_onehot.values
print(sex_onehot[:5])

[[0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]]


In [40]:
# Analysis and preparation of column "Age":

age = data_x[:,4]
age = age.reshape(age.shape[0],1)
print(age[:5])

[[22.0]
 [38.0]
 [26.0]
 [35.0]
 [35.0]]


In [51]:
# Analysis and preparation of column "SibSp":

sibsp = data_x[:,5]
sibsp_onehot = pd.get_dummies(sibsp)
sibsp_onehot = sibsp_onehot.values

print(sibsp_onehot[:5])

[[0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0]]


In [52]:
# Analysis and preparation of column "Parch"

parch = data_x[:,6]
parch_onehot = pd.get_dummies(parch)
parch_onehot = parch_onehot.values

print(parch_onehot[:5])

[[1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [53]:
# Analysis and preparation of column "Ticket":

ticket = data_x[:,7]

#complete later

In [68]:
# Analysis and preparation of column "Embarked"

embarked = data_x[:,10]
embarked_onehot = pd.get_dummies(embarked)
v_onehot = embarked_onehot.values

print(embarked_onehot[:5])


   C  Q  S
0  0  0  1
1  1  0  0
2  0  0  1
3  0  0  1
4  0  0  1


In [104]:
pclass_onehot = np.array(pclass_onehot, dtype=float)
sex_onehot = np.array(sex_onehot, dtype=float)
age = np.array(age, dtype=float)
sibsp_onehot = np.array(sibsp_onehot, dtype=float)
parch_onehot = np.array(parch_onehot, dtype=float)
embarked_onehot = np.array(embarked_onehot, dtype=float)

data_x_final = np.concatenate((pclass_onehot, sex_onehot, sibsp_onehot, parch_onehot), axis = 1)

print("data_x_final shape: " + str(data_x_final.shape))
print(data_x_final[:5])

data_x_final shape: (1309, 15)
[[ 0.  0.  1.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  1.  0.  0.  1.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  1.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  1.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [105]:
# Split into train and test sets

x_train = data_x_final[0:original_training_rows,:]
x_test = data_x_final[original_training_rows:,:]


In [106]:
print(data_train_y.shape)
print(x_train.shape)

print(type(x_train))

#sum(np.isnan(x_train))

np.isnan(np.min(x_train))
#np.max(x_train)

(891, 1)
(891, 15)
<class 'numpy.ndarray'>


False

In [128]:
# Fit a logistic regression model

from sklearn import linear_model

data_train_y = data_train_y.reshape(data_train_y.shape[0],)

logreg = linear_model.LogisticRegression(C=1e5)
logreg.fit(x_train, data_train_y)

LogisticRegression(C=100000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [129]:
# Apply the trained model to the test set

predicted = logreg.predict(x_test)

predicted_passengerid = data_test.PassengerId.values
predicted_passengerid = predicted_passengerid.reshape(predicted_passengerid.shape[0],1)

predicted_passengerid.shape
predicted = predicted.reshape(predicted.shape[0],1)

predicted_df = np.concatenate((predicted_passengerid ,predicted), axis = 1)
predicted_df = pd.DataFrame(predicted_df)
predicted_df.columns = ['PassengerId','Survived']
predicted_df.head(n=5)

predicted_df.to_csv('submission_logreg.csv', index=False)